// Code generated by "stringer -type=errEnum"; DO NOT EDIT.

package retry

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AllStates-0]
	_ = x[LastState-1]
	_ = x[NoStates-2]
	_ = x[AllErrors-3]
	_ = x[LastError-4]
	_ = x[testErrors-999]
}

const (
	_errEnum_name_0 = "AllStatesLastStateNoStatesAllErrorsLastError"
	_errEnum_name_1 = "testErrors"
)

var (
	_errEnum_index_0 = [...]uint8{0, 9, 18, 26, 35, 44}
)

func (i errEnum) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _errEnum_name_0[_errEnum_index_0[i]:_errEnum_index_0[i+1]]
	case i == 999:
		return _errEnum_name_1
	default:
		return "errEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
